### PR TITLE
Add dndx to Tracks as a edm4hep::Quantity

### PR DESCRIPTION
**Pull request by clementhelsens**
BEGINRELEASENOTES
- Untested code as it needs https://github.com/key4hep/EDM4hep/pull/137
- but can still look if the code makes sense (not sure about the ```addToQuantity```
ENDRELEASENOTES

### CODE REVIEW

**Comment by tmadlener** [comment]
I think the `addToQuantity` should work as it is at the moment. The current version of this pull request has a few conflicts with the main branch though. It looks like it still contains all the changes from #81. Could you resolve the conflicts, I don't think the CI will run otherwise (even if it will fail at this point)

**Comment by clementhelsens** [comment]
I solved the conflict and also commented out the dndx user data as the quantity should take it

**Comment by clementhelsens** [comment]
Removed the commented dndx userdata and not WIP anylonger

**Comment by tmadlener** [comment]
The key4hep nightlies have now picked up the necessary version of EDM4hep. In principle we could add checks on the additional information that we now store into the comparison check, but that can also be done later (in which case I would open an issue to keep track of it).

In any case waiting for the key4hep nightlies CI workflow to finish and make sure that it is OK before merging.

**Review by tmadlener — APPROVED** [review]

**Pull request merged**
